-- MySQL Script generated by MySQL Workbench
-- Sat Sep 22 03:03:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GoodWill
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GoodWill
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GoodWill` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `GoodWill` ;

-- -----------------------------------------------------
-- Table `GoodWill`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodWill`.`Client` (
  `idClient` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Rate of Donation` DECIMAL NOT NULL,
  `Time (Donation Recieved)` DATE NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodWill`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodWill`.`Employee` (
  `idEmployee` INT AUTO_INCREMENT PRIMARY KEY,
  `Name` VARCHAR(45) NOT NULL,
  `idStore` INT NOT NULL DEFAULT 0
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodWill`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodWill`.`Store` (
  `idStore` INT NOT NULL,
  `idEmployee` INT NULL,
  `idClient` INT NULL,
  `ZipCode` INT NULL,
  PRIMARY KEY (`idStore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodWill`.`Reciept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoodWill`.`Reciept` (
  `idReciept` INT NOT NULL,
  `idClient` INT NULL,
  `idEmployee` INT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Store_idStore` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idReciept`, `Employee_idEmployee`, `Store_idStore`, `Client_idClient`),
  INDEX `fk_Reciept_Employee_idx` (`Employee_idEmployee` ASC) VISIBLE,
  INDEX `fk_Reciept_Store1_idx` (`Store_idStore` ASC) VISIBLE,
  INDEX `fk_Reciept_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Reciept_Employee`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `GoodWill`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reciept_Store1`
    FOREIGN KEY (`Store_idStore`)
    REFERENCES `GoodWill`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reciept_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `GoodWill`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
